id = "typos"
name = "Typos"
description = "Typos Language Server support for Zed editor"
version = "0.0.3"
schema_version = 1
authors = ["Baptiste Roseau <broseau@gmail.com>"]
repository = "https://github.com/BaptisteRoseau/zed-typos"

[language_servers.typos]
name = "typos"
languages = [
    "AsciiDoc",
    "Astro",
    "Bash",
    "Biome",
    "C",
    "C#",
    "C++",
    "Clojure",
    "CSharp",
    "CSS",
    "CSV",
    "D",
    "Dart",
    "Deno",
    "Docker",
    "Elixir",
    "Elm",
    "Emmet",
    "Erlang",
    "Fish",
    "FSharp",
    "GDScript",
    "Git Commit",
    "Gleam",
    "GLSL",
    "Go",
    "GraphQL",
    "Groovy",
    "Haskell",
    "HEEX",
    "HTML",
    "Hy",
    "Idris",
    "Java",
    "JavaScript",
    "JSON",
    "JSONC",
    "Julia",
    "Kotlin",
    "LaTeX",
    "Lua",
    "Luau",
    "Makefile",
    "Markdown",
    "Nim",
    "Nix",
    "OCaml",
    "PHP",
    "Plain Text",
    "Prisma",
    "Proto",
    "PureScript",
    "Python",
    "R",
    "Racket",
    "Rego",
    "reST",
    "ReStructuredText",
    "Roc",
    "Ruby",
    "Rust",
    "Scala",
    "Scheme",
    "SCSS",
    "Shell Script",
    "SQL",
    "Svelte",
    "Swift",
    "TailwindCSS",
    "Terraform",
    "TOML",
    "TSX",
    "TypeScript",
    "Uiua",
    "Vue",
    "WIT",
    "XML",
    "YAML",
    "Yarn",
    "Zig",
]
