id = "typos"
name = "Typos"
description = "Typos Language Server support for Zed editor"
version = "0.0.1"
schema_version = 1
authors = ["Baptiste Roseau <broseau@gmail.com>"]
repository = "https://github.com/BaptisteRoseau/zed-typos"

[language_servers.typos]
name = "typos"
languages = [
    "C",
    "CSS",
    "CSV",
    "CSharp",
    "Clojure",
    "D",
    "Dart",
    "Elixir",
    "Elm",
    "Erlang",
    "FSharp",
    "Fish",
    "GDScript",
    "Git Commit",
    "Gleam",
    "Go",
    "GraphQL",
    "HEEX",
    "HTML",
    "HTML",
    "Haskell",
    "Hy",
    "Idris",
    "JSON",
    "JSONC",
    "Java",
    "JavaScript",
    "Julia",
    "Kotlin",
    "LaTeX",
    "Lua",
    "Markdown",
    "Nim",
    "Nix",
    "OCaml",
    "Plain Text",
    "PureScript",
    "Racket",
    "Roc",
    "Ruby",
    "Rust",
    "SCSS",
    "SQL",
    "Scheme",
    "Shell Script",
    "Swift",
    "TOML",
    "TSX",
    "TypeScript",
    "WIT",
    "XML",
    "YAML",
    "Zig",
    "reST",
]
